---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Initialize Packer project
      ansible.builtin.command:
        cmd: "packer init /home/rloyaute/pfsense-packer-proxmox/pfSense.pkr.hcl"
      ignore_errors: yes
      # Consider handling errors more appropriately.

    - name: Build pfSense image with Packer
      ansible.builtin.command:
        cmd: "packer build -var-file=variables.pkr.hcl -var-file=credentials.pkr.hcl pfSense.pkr.hcl"
        chdir: "/home/rloyaute/Proxmox-Hetzner-Ansible/pf-packer"
      ignore_errors: yes

- hosts: hetzner_servers
  gather_facts: no
  become: yes
  tasks:

    - name: Clone VM template to new VM named pfSense
      ansible.builtin.command:
        cmd: "qm clone 900 100 --name pfSense --full true"
      ignore_errors: yes

    - name: Start the new pfSense VM
      ansible.builtin.command:
        cmd: "qm start 100"
      ignore_errors: yes

    - name: Create pfSense routing script
      copy:
        dest: /root/pfsense-route.sh
        content: |
          #!/bin/sh

          ## enable IP forwarding
          echo 1 > /proc/sys/net/ipv4/ip_forward

          ## Redirect intended packets to LAN for the WAN pfSense interface
          ip route change 192.168.10.0/24 via 10.0.0.2 dev vmbr1
        mode: '0755'

    - name: Create IPTABLES configuration script
      ansible.builtin.template:
        src: templates/iptables.sh.j2
        dest: /root/iptables.sh
        mode: '0755'

    - name: Backup critical network configuration files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ item }}.bak"
        remote_src: yes
      loop:
        - /etc/network/interfaces
        - /root/pfsense-route.sh
        - /root/iptables.sh
      when: ansible_check_mode is not defined or not ansible_check_mode

    - name: Execute pfSense routing configuration script
      ansible.builtin.command:
        cmd: /root/pfsense-route.sh
      ignore_errors: yes

    - name: Execute IPTABLES configuration script
      ansible.builtin.command:
        cmd: /root/iptables.sh
      ignore_errors: yes