- hosts: hetzner_servers
  gather_facts: yes
  become: yes
  
  tasks:
    - name: Gather network facts
      ansible.builtin.setup:
        filter: "ansible_*_ipv4"

    - name: Get IP routes
      ansible.builtin.command: ip route
      register: ip_routes

    - name: Display network information
      ansible.builtin.debug:
        msg: |
          Interface: "{{ item.key }}"
          IPv4 Address: "{{ item.value.address }}"
          IPv4 Broadcast: "{{ item.value.broadcast }}"
          IPv4 Netmask: "{{ item.value.netmask }}"
          IPv4 Network: "{{ item.value.network }}"
      loop: "{{ ansible_facts | dict2items }}"
      when: item.key is match("^ansible_.*_ipv4$") and item.value is not none

    - name: Display IP routes
      ansible.builtin.debug:
        var: ip_routes.stdout_lines

    - name: Update and upgrade all packages to the latest version
      ansible.builtin.apt:
        update_cache: yes
        upgrade: full
        force_apt_get: yes

    - name: Install necessary packages for Proxmox installation
      ansible.builtin.apt:
        name:
          - curl
          - gnupg2
        state: present

    - name: Add Proxmox VE repository for Debian Bookworm
      ansible.builtin.shell: |
        echo "deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription" > /etc/apt/sources.list.d/pve-install-repo.list
        curl http://download.proxmox.com/debian/proxmox-release-bookworm.gpg | gpg --dearmor > /etc/apt/trusted.gpg.d/proxmox-release-bookworm.gpg
      args:
        executable: /bin/bash

    - name: Update APT cache after adding Proxmox VE repository
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Proxmox VE
      ansible.builtin.apt:
        name:
          - proxmox-ve
          - postfix
          - open-iscsi
        state: present

    - name: Remove the default Debian kernel
      ansible.builtin.apt:
        name:
          - linux-image-amd64
          - linux-image-$(uname -r)
        state: absent
      ignore_errors: yes

    - name: Update GRUB and remove os-prober
      ansible.builtin.shell: |
        update-grub
        apt remove os-prober -y
      args:
        executable: /bin/bash

    - name: Reboot the server to complete Proxmox VE installation
      ansible.builtin.reboot:
        msg: "Rebooting to complete Proxmox VE installation"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
